spring:
  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${APP_POSTGRESQL_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    default_schema: ${APP_POSTGRESQL_SCHEMA}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION}

app:
  init-fake-data: false